services:
    node:
        build: ./app/
    node2:
        build: ./app/
    node3:
        build: ./app/
    node4:
        build: ./app/
        ports:
        - "3000:3000"
    node5:
        build: ./app/
    node6:
        build: ./app/